### ISSUE TITLE
[BUILD] Release 0.0.74 does not build

### ISSUE THREAD

**Issue by firsou** [chrberger/libcluon#1]
_Description_: When building from source, build fails at step "Building CXX object CMakeFiles/TestOD4Session.cpp-Runner.dir/testsuites/TestOD4Session.cpp.o"

_Steps I performed_:

* Downloaded 0.0.74 Release
* Created "build" directory in libcluon root directory
* `cmake ../libcluon`
* `make`
* Recipe fails at 84% when building CXX Object CMakeFiles/TestOD4Session.cpp-Runner.dir/testsuites/TestOD4Session.cpp.o

_Error Message_ : [Pastebin](https://pastebin.com/PNDvnUH6)

**Comment by chrberger** [comment]
What Linux are you using?
What compiler and what version are you using?

**Comment by firsou** [comment]
I am using Ubuntu 17.10, but others on 16.04 are reporting the same error to me.

The compiler I am using is G++ 7.2.0

**Comment by chrberger** [comment]
The sources certainly build cleanly on Ubuntu 16.04 as I am using that myself.

The build error originates from G++ 7.2.0 warnings.

**Comment by firsou** [comment]
My mistake, you're right, the error on 16.04 originated from a Docker image rather than building libcluon directly.

Should I downgrade to G++ 5.3.1 then ?

**Comment by chrberger** [comment]
I fixed the compile warnings with 2933916f476ba69c5ce95a703a6d18a0193f0e42, 2277250e4cb5ad83ef59be430d43c3d93e289c11, and 6291bd41b9b1134336d86c463c357571abbac925
