### ISSUE TITLE
Compiler warning: -Wreturn-type (v0.0.140)

### ISSUE THREAD

**Issue by freol35241** [chrberger/libcluon#11]
Using gcc 9.3.0 on Ubuntu 20.04 (wsl2) and `cluon-complete.hpp` from the latest release (v0.0.140). The compiler gives me the following warning related to a switch statement without default case in a lambda function:

```
[build] /build/cluon-complete.cpp: In lambda function:
[build] /build/cluon-complete.cpp:3692:5: warning: control reaches end of non-void function [-Wreturn-type]
[build]  3692 |     };
[build]       |     ^
```

**Comment by chrberger** [comment]
Thanks for the feedback; the warning is issued from an externally sourced 3rd party library: https://github.com/chrberger/libcluon/blob/master/libcluon/thirdparty/cpp-peglib/peglib.h#L3128-L3143
