### ISSUE TITLE
No switch for disabling the tests in a CMake build?

### ISSUE THREAD

**Issue by freol35241** [chrberger/libcluon#12]
Using the CMakeLists.txt from the libcluon folder I cant seem to find a way to disable the tests from being configured. This would make life easier when building from source instead of using the single-file, header-only distribution.

**Comment by chrberger** [comment]
Added with https://github.com/chrberger/libcluon/commit/fbed1f50c0ace0b318ff2b9b709fa4808bfa359e 
cmake -D SKIP_TESTS=1 ..
