### ISSUE TITLE
Could you please add the cluon-complete.hpp to the release file?

### ISSUE THREAD

**Issue by toge** [chrberger/libcluon#16]
I intend to add the libcluon recipe to the conan repsitory.
The version number is important for the conan recipe.
Currently, the url in the cluon-complete.hpp is not tagged by version.

Could you please add the cluon-complete.hpp to the release file like the nlohmann/json release?
https://github.com/nlohmann/json/releases/tag/v3.10.5

**Comment by chrberger** [comment]
Fixed: https://github.com/chrberger/libcluon/releases/tag/v0.0.140

**Comment by toge** [comment]
Thanks a lot!
